In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [6]:
df = pd.read_csv("C:/Users/91970/OneDrive/Documents/spam1.csv")

In [7]:
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will �_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [8]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [9]:
df.drop("Unnamed: 2",axis=1,inplace=True)

In [10]:
df.drop("Unnamed: 3",axis=1,inplace=True)

In [11]:
df.drop("Unnamed: 4",axis=1,inplace=True)

In [12]:
df.columns

Index(['v1', 'v2'], dtype='object')

In [13]:
df.columns = ["Category","Message"]

In [14]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will �_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [15]:
df["Category"].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [16]:
df.isna().sum()

Category    0
Message     0
dtype: int64

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
label=LabelEncoder()

In [19]:
label.fit(df["Category"])

LabelEncoder()

In [20]:
ary = label.transform(df["Category"])

In [21]:
df["Categories"] = ary

In [22]:
df

Category                                            Message  Categories
0         ham  Go until jurong point, crazy.. Available only ...           0
1         ham                      Ok lar... Joking wif u oni...           0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...           1
3         ham  U dun say so early hor... U c already then say...           0
4         ham  Nah I don't think he goes to usf, he lives aro...           0
...       ...                                                ...         ...
5567     spam  This is the 2nd time we have tried 2 contact u...           1
5568      ham              Will �_ b going to esplanade fr home?           0
5569      ham  Pity, * was in mood for that. So...any other s...           0
5570      ham  The guy did some bitching but I acted like i'd...           0
5571      ham                         Rofl. Its true to its name           0

[5572 rows x 3 columns]

In [23]:
df.drop("Category",axis=1,inplace=True)

In [24]:
df

Message  Categories
0     Go until jurong point, crazy.. Available only ...           0
1                         Ok lar... Joking wif u oni...           0
2     Free entry in 2 a wkly comp to win FA Cup fina...           1
3     U dun say so early hor... U c already then say...           0
4     Nah I don't think he goes to usf, he lives aro...           0
...                                                 ...         ...
5567  This is the 2nd time we have tried 2 contact u...           1
5568              Will �_ b going to esplanade fr home?           0
5569  Pity, * was in mood for that. So...any other s...           0
5570  The guy did some bitching but I acted like i'd...           0
5571                         Rofl. Its true to its name           0

[5572 rows x 2 columns]

In [24]:
X = df[["Message"]]

In [25]:
X

Message
0     Go until jurong point, crazy.. Available only ...
1                         Ok lar... Joking wif u oni...
2     Free entry in 2 a wkly comp to win FA Cup fina...
3     U dun say so early hor... U c already then say...
4     Nah I don't think he goes to usf, he lives aro...
...                                                 ...
5567  This is the 2nd time we have tried 2 contact u...
5568              Will �_ b going to esplanade fr home?
5569  Pity, * was in mood for that. So...any other s...
5570  The guy did some bitching but I acted like i'd...
5571                         Rofl. Its true to its name

[5572 rows x 1 columns]

In [26]:
y = df["Categories"]

In [27]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Categories, Length: 5572, dtype: int32

In [28]:
y.value_counts()

0    4825
1     747
Name: Categories, dtype: int64

In [29]:
from imblearn.over_sampling import RandomOverSampler

In [30]:
ros = RandomOverSampler()

In [31]:
X_ros,y_ros = ros.fit_resample(X,y)

In [32]:
X_ros.shape

(9650, 1)

In [33]:
y_ros.shape

(9650,)

In [34]:
y_ros.value_counts()

0    4825
1    4825
Name: Categories, dtype: int64

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train,X_test,y_train,y_test = train_test_split(X_ros,y_ros,test_size=0.20,random_state=2)

In [37]:
X_train.shape,X_test.shape,X_ros.shape

((7720, 1), (1930, 1), (9650, 1))

In [38]:
y_train.shape,y_test.shape,y_ros.shape

((7720,), (1930,), (9650,))

In [39]:
X_ros

Message
0     Go until jurong point, crazy.. Available only ...
1                         Ok lar... Joking wif u oni...
2     Free entry in 2 a wkly comp to win FA Cup fina...
3     U dun say so early hor... U c already then say...
4     Nah I don't think he goes to usf, he lives aro...
...                                                 ...
9645  Thanks for your ringtone order, ref number R83...
9646  Ur TONEXS subscription has been renewed and yo...
9647  U are subscribed to the best Mobile Content Se...
9648  You are a �1000 winner or Guaranteed Caller Pr...
9649  Wan2 win a Meet+Greet with Westlife 4 U or a m...

[9650 rows x 1 columns]

In [40]:
X_train["Message"]

9598    Fantasy Football is back on your TV. Go to Sky...
6115    Someone U know has asked our dating service 2 ...
1482                                                Ok...
6732    Auction round 4. The highest bid is now �54. N...
7878    Fantasy Football is back on your TV. Go to Sky...
                              ...                        
1099    Been up to ne thing interesting. Did you have ...
2514        Ok ill send you with in  &lt;DECIMAL&gt;  ok.
6637    Hi if ur lookin 4 saucy daytime fun wiv busty ...
2575                 Now thats going to ruin your thesis!
7336    URGENT, IMPORTANT INFORMATION FOR O2 USER. TOD...
Name: Message, Length: 7720, dtype: object

In [41]:
X_train["Message"].values

array(['Fantasy Football is back on your TV. Go to Sky Gamestar on Sky Active and play �250k Dream Team. Scoring starts on Saturday, so register now!SKY OPT OUT to 88088',
       'Someone U know has asked our dating service 2 contact you! Cant Guess who? CALL 09058097189 NOW all will be revealed. POBox 6, LS15HB 150p ',
       'Ok...', ...,
       'Hi if ur lookin 4 saucy daytime fun wiv busty married woman Am free all next week Chat now 2 sort time 09099726429 JANINExx Calls�1/minMobsmoreLKPOBOX177HP51FL',
       'Now thats going to ruin your thesis!',
       'URGENT, IMPORTANT INFORMATION FOR O2 USER. TODAY IS YOUR LUCKY DAY! 2 FIND OUT WHY LOG ONTO HTTP://WWW.URAWINNER.COM THERE IS A FANTASTIC SURPRISE AWAITING FOR YOU'],
      dtype=object)

In [42]:
X_train.values

array([['Fantasy Football is back on your TV. Go to Sky Gamestar on Sky Active and play �250k Dream Team. Scoring starts on Saturday, so register now!SKY OPT OUT to 88088'],
       ['Someone U know has asked our dating service 2 contact you! Cant Guess who? CALL 09058097189 NOW all will be revealed. POBox 6, LS15HB 150p '],
       ['Ok...'],
       ...,
       ['Hi if ur lookin 4 saucy daytime fun wiv busty married woman Am free all next week Chat now 2 sort time 09099726429 JANINExx Calls�1/minMobsmoreLKPOBOX177HP51FL'],
       ['Now thats going to ruin your thesis!'],
       ['URGENT, IMPORTANT INFORMATION FOR O2 USER. TODAY IS YOUR LUCKY DAY! 2 FIND OUT WHY LOG ONTO HTTP://WWW.URAWINNER.COM THERE IS A FANTASTIC SURPRISE AWAITING FOR YOU']],
      dtype=object)

In [43]:
X_train["Message"].values

array(['Fantasy Football is back on your TV. Go to Sky Gamestar on Sky Active and play �250k Dream Team. Scoring starts on Saturday, so register now!SKY OPT OUT to 88088',
       'Someone U know has asked our dating service 2 contact you! Cant Guess who? CALL 09058097189 NOW all will be revealed. POBox 6, LS15HB 150p ',
       'Ok...', ...,
       'Hi if ur lookin 4 saucy daytime fun wiv busty married woman Am free all next week Chat now 2 sort time 09099726429 JANINExx Calls�1/minMobsmoreLKPOBOX177HP51FL',
       'Now thats going to ruin your thesis!',
       'URGENT, IMPORTANT INFORMATION FOR O2 USER. TODAY IS YOUR LUCKY DAY! 2 FIND OUT WHY LOG ONTO HTTP://WWW.URAWINNER.COM THERE IS A FANTASTIC SURPRISE AWAITING FOR YOU'],
      dtype=object)

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

In [45]:
cvec=CountVectorizer()

In [47]:
cvec.fit(X_train["Message"].values)

CountVectorizer()

In [48]:
cvec_Xtrain = cvec.transform(X_train["Message"].values)

In [49]:
cvec_Xtest = cvec.transform(X_test["Message"].values)

In [50]:
cvec_Xtrain

<7720x7940 sparse matrix of type '<class 'numpy.int64'>'
	with 130142 stored elements in Compressed Sparse Row format>

In [51]:
cvec_Xtest

<1930x7940 sparse matrix of type '<class 'numpy.int64'>'
	with 31845 stored elements in Compressed Sparse Row format>

In [52]:
cvec_Xtrain.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [53]:
cvec_Xtrain.toarray().shape

(7720, 7940)

In [54]:
cvec_Xtest.toarray().shape

(1930, 7940)

In [55]:
cvec.vocabulary_

{'fantasy': 2915,
 'football': 3074,
 'is': 3890,
 'back': 1291,
 'on': 5103,
 'your': 7907,
 'tv': 7265,
 'go': 3291,
 'to': 7113,
 'sky': 6381,
 'gamestar': 3202,
 'active': 894,
 'and': 1055,
 'play': 5413,
 '250k': 421,
 'dream': 2574,
 'team': 6918,
 'scoring': 6114,
 'starts': 6626,
 'saturday': 6088,
 'so': 6453,
 'register': 5846,
 'now': 5008,
 'opt': 5138,
 'out': 5179,
 '88088': 785,
 'someone': 6469,
 'know': 4105,
 'has': 3485,
 'asked': 1192,
 'our': 5176,
 'dating': 2301,
 'service': 6199,
 'contact': 2097,
 'you': 7903,
 'cant': 1751,
 'guess': 3410,
 'who': 7686,
 'call': 1714,
 '09058097189': 213,
 'all': 1006,
 'will': 7707,
 'be': 1372,
 'revealed': 5944,
 'pobox': 5440,
 'ls15hb': 4396,
 '150p': 349,
 'ok': 5084,
 'auction': 1232,
 'round': 6001,
 'the': 6994,
 'highest': 3569,
 'bid': 1444,
 '54': 621,
 'next': 4930,
 'maximum': 4550,
 '71': 685,
 'send': 6178,
 'bids': 1445,
 '10': 297,
 '83383': 749,
 'good': 3317,
 'luck': 4404,
 'important': 3773,
 'informatio

In [56]:
cvec.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zoom', 'zouk', 'zyada'], dtype=object)

In [57]:
cvec.get_feature_names_out().shape

(7940,)

In [58]:
cvec_Xtrain

<7720x7940 sparse matrix of type '<class 'numpy.int64'>'
	with 130142 stored elements in Compressed Sparse Row format>

In [59]:
cvec_Xtest

<1930x7940 sparse matrix of type '<class 'numpy.int64'>'
	with 31845 stored elements in Compressed Sparse Row format>

In [60]:
from sklearn.feature_extraction.text import TfidfTransformer

In [62]:
trans=TfidfTransformer()

In [63]:
trans.fit(cvec_Xtrain)

TfidfTransformer()

In [64]:
trans_Xtrain = trans.transform(cvec_Xtrain)

In [65]:
trans_Xtest = trans.transform(cvec_Xtest)

In [66]:
trans_Xtrain.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [67]:
trans_Xtest.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [68]:
from sklearn.naive_bayes import MultinomialNB

In [69]:
mnb = MultinomialNB()

In [70]:
mnb

MultinomialNB()

In [71]:
mnb.fit(trans_Xtrain,y_train)

MultinomialNB()

In [72]:
mnb.score(trans_Xtest,y_test)

0.9797927461139896